linters:
  enable:
  - megacheck
  - govet
  - bodyclose
  - unparam
  - unconvert
  - misspell
  - lll
  - gofmt
  - gochecknoinits
  - golint
  - gosec
  - nakedret
  - gomnd
  - maligned
  - errcheck
linters-settings:
  lll:
    line-length: 150