version: "2"
run:
  timeout: 8m
  build-tags:
    - enterprise
linters:
  enable:
    - asciicheck
    - bodyclose
    - contextcheck
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gochecknoinits
    - gomodguard
    - gosec
    - importas
    - lll
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - wastedassign
  settings:
    gomodguard:
      blocked:
        modules:
          - github.com/ghodss/yaml:
              recommendations:
                - sigs.k8s.io/yaml
          - gopkg.in/yaml.v2:
              recommendations:
                - sigs.k8s.io/yaml
          - gopkg.in/yaml.v3:
              recommendations:
                - sigs.k8s.io/yaml
          - github.com/pkg/errors:
              recommendations:
                - fmt
                - errors
          - golang.org/x/net/context:
              recommendations:
                - context
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: "^\t*// "
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kong)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
