linters:
  enable:
  - asciicheck
  - bodyclose
  - depguard
  - dogsled
  - durationcheck
  - errcheck
  - exhaustive
  - exportloopref
  - gci
  - gochecknoinits
  - gofmt
  - gofumpt
  - goimports
  - gomnd
  - gosec
  - govet
  - importas
  - lll
  - megacheck
  - misspell
  - nakedret
  - nilerr
  - nolintlint
  - predeclared
  - revive
  - stylecheck
  - unconvert
  - unparam
  - wastedassign
