run:
  timeout: 5m
  build-tags:
  - enterprise

linters:
  enable:
  - asciicheck
  - bodyclose
  - contextcheck
  - depguard
  - dogsled
  - durationcheck
  - errcheck
  - errname
  - errorlint
  - exhaustive
  - exportloopref
  - gci
  - gochecknoinits
  - gofmt
  - gofumpt
  - goimports
  - gomnd
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - lll
  - megacheck
  - misspell
  - nakedret
  - nilerr
  - nolintlint
  - predeclared
  - revive
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - wastedassign

issues:
  max-same-issues: 0
